
import { CharacterTemplate, AbilityKey, StatusType, ArenaLayout } from './types';

export const ARENA_WIDTH = 1200;
export const ARENA_HEIGHT = 800;

export const ARENAS: ArenaLayout[] = [
  {
    id: 'empty',
    name: 'Gate Room Zero',
    obstacles: []
  },
  {
    id: 'pillars',
    name: 'Ancient Hall',
    obstacles: [
      { x: 300, y: 200, width: 60, height: 60, type: 'pillar' },
      { x: 300, y: 540, width: 60, height: 60, type: 'pillar' },
      { x: 840, y: 200, width: 60, height: 60, type: 'pillar' },
      { x: 840, y: 540, width: 60, height: 60, type: 'pillar' },
      { x: 570, y: 370, width: 60, height: 60, type: 'pillar' },
    ]
  },
  {
    id: 'divided',
    name: 'The Event Horizon',
    obstacles: [
      { x: 400, y: 0, width: 40, height: 250, type: 'wall' },
      { x: 400, y: 550, width: 40, height: 250, type: 'wall' },
      { x: 760, y: 0, width: 40, height: 250, type: 'wall' },
      { x: 760, y: 550, width: 40, height: 250, type: 'wall' },
      { x: 500, y: 380, width: 200, height: 40, type: 'wall' },
    ]
  }
];

export const CHARACTERS: CharacterTemplate[] = [
  {
    id: 'ignis',
    name: 'Solar Warden',
    role: 'Energy Weaver',
    bio: 'A celestial being who harnessed the power of a dying sun before stepping through the Gate.',
    difficulty: 2,
    color: '#ff4d00',
    accentColor: '#ffcc00',
    modelType: 'mage',
    avatar: 'https://images.unsplash.com/photo-1614728263952-84ea256f9679?auto=format&fit=crop&q=80&w=400&h=400',
    stats: {
      maxHp: 1000,
      hp: 1000,
      maxMana: 500,
      mana: 500,
      manaRegen: 60,
      speed: 850,
      baseAttackDamage: 45,
      attackRange: 320,
      attackSpeed: 1.3,
    },
    abilities: [
      {
        id: AbilityKey.A,
        name: 'Plasma Bolt',
        description: 'Launches a solar flare.',
        cooldown: 400,
        currentCooldown: 0,
        manaCost: 15,
        damage: 65,
        type: 'projectile',
        speed: 1800,
        range: 850,
        color: '#ff6a00',
        icon: '☄️',
        effect: { type: StatusType.BURN, timer: 1500, value: 10 }
      },
      {
        id: AbilityKey.S,
        name: 'Flame Step',
        description: 'Instant molecular shift.',
        cooldown: 2200,
        currentCooldown: 0,
        manaCost: 35,
        damage: 10,
        type: 'dash',
        range: 400,
        color: '#ffcc00',
        icon: '✨',
        bypassesWalls: true
      },
      {
        id: AbilityKey.D,
        name: 'Cinder Blast',
        description: 'Explosive radial heat.',
        cooldown: 3800,
        currentCooldown: 0,
        manaCost: 50,
        damage: 100,
        type: 'aoe',
        radius: 180,
        color: '#ff3300',
        icon: '🔆',
        effect: { type: StatusType.BURN, timer: 2000, value: 20 }
      },
      {
        id: AbilityKey.F,
        name: 'Nova Strike',
        description: 'Orbital energy drop.',
        cooldown: 7000,
        currentCooldown: 0,
        manaCost: 90,
        damage: 250,
        type: 'target-delayed',
        radius: 140,
        color: '#990000',
        icon: '🔥',
        effect: { type: StatusType.STUN, timer: 700 }
      }
    ]
  },
  {
    id: 'zephyr',
    name: 'Void Stalker',
    role: 'Galactic Scout',
    bio: 'A cybernetic traveler using a personal Gate-drive to manipulate the void.',
    difficulty: 3,
    color: '#00ccff',
    accentColor: '#ffffff',
    modelType: 'ranger',
    avatar: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&q=80&w=400&h=400',
    stats: {
      maxHp: 850,
      hp: 850,
      maxMana: 400,
      mana: 400,
      manaRegen: 70,
      speed: 950,
      baseAttackDamage: 60,
      attackRange: 450,
      attackSpeed: 1.7,
    },
    abilities: [
      {
        id: AbilityKey.A,
        name: 'Sonic Blade',
        description: 'Fires a high-frequency wave.',
        cooldown: 300,
        currentCooldown: 0,
        manaCost: 10,
        damage: 45,
        type: 'projectile',
        speed: 2200,
        range: 1000,
        color: '#e0f7fa',
        icon: '🔪',
      },
      {
        id: AbilityKey.S,
        name: 'Warp Drive',
        description: 'Boosts movement systems.',
        cooldown: 4500,
        currentCooldown: 0,
        manaCost: 30,
        damage: 0,
        type: 'self-buff',
        color: '#81d4fa',
        icon: '🚀',
        effect: { type: StatusType.SPEED, timer: 2000, value: 350 }
      },
      {
        id: AbilityKey.D,
        name: 'Gravity Well',
        description: 'Vortex that slows.',
        cooldown: 4200,
        currentCooldown: 0,
        manaCost: 45,
        damage: 25,
        type: 'aoe',
        radius: 130,
        color: '#b3e5fc',
        icon: '🌪️',
        effect: { type: StatusType.SLOW, timer: 1200, value: 0.6 }
      },
      {
        id: AbilityKey.F,
        name: 'Singularity',
        description: 'Barrage of void energy.',
        cooldown: 8500,
        currentCooldown: 0,
        manaCost: 80,
        damage: 320,
        type: 'aoe',
        radius: 300,
        color: '#01579b',
        icon: '🌌',
      }
    ]
  },
  {
    id: 'terra',
    name: 'Gate Guardian',
    role: 'Earthen Warden',
    bio: 'The ancient defender of the first Gate, constructed from living stone.',
    difficulty: 1,
    color: '#8d6e63',
    accentColor: '#3e2723',
    modelType: 'warrior',
    avatar: 'https://images.unsplash.com/photo-1555679427-1f6dfcce043a?auto=format&fit=crop&q=80&w=400&h=400',
    stats: {
      maxHp: 1600,
      hp: 1600,
      maxMana: 350,
      mana: 350,
      manaRegen: 45,
      speed: 750,
      baseAttackDamage: 95,
      attackRange: 150,
      attackSpeed: 1.2,
    },
    abilities: [
      {
        id: AbilityKey.A,
        name: 'Monolith Toss',
        description: 'Throws a shard of stone.',
        cooldown: 1500,
        currentCooldown: 0,
        manaCost: 20,
        damage: 90,
        type: 'projectile',
        speed: 1600,
        range: 700,
        color: '#5d4037',
        icon: '🪨',
      },
      {
        id: AbilityKey.S,
        name: 'Gate Shield',
        description: 'Hardens stone exterior.',
        cooldown: 5500,
        currentCooldown: 0,
        manaCost: 40,
        damage: 0,
        type: 'self-buff',
        color: '#795548',
        icon: '🛡️',
        effect: { type: StatusType.SHIELD, timer: 3000, value: 500 }
      },
      {
        id: AbilityKey.D,
        name: 'Tectonic Slam',
        description: 'Ground slam that slows.',
        cooldown: 4500,
        currentCooldown: 0,
        manaCost: 50,
        damage: 150,
        type: 'aoe',
        radius: 240,
        color: '#4e342e',
        icon: '🌋',
        effect: { type: StatusType.SLOW, timer: 1000, value: 0.5 }
      },
      {
        id: AbilityKey.F,
        name: 'Gate Lockdown',
        description: 'Crushes target in stone.',
        cooldown: 10000,
        currentCooldown: 0,
        manaCost: 75,
        damage: 300,
        type: 'target-delayed',
        radius: 140,
        color: '#263238',
        icon: '⛓️',
        effect: { type: StatusType.STUN, timer: 900 }
      }
    ]
  },
  {
    id: 'vesper',
    name: 'Vesper',
    role: 'Nightshade Assassin',
    bio: 'A ghost who moves through the cracks of reality, striking before being seen.',
    difficulty: 3,
    color: '#4a148c',
    accentColor: '#ab47bc',
    modelType: 'assassin',
    avatar: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=400&h=400',
    stats: {
      maxHp: 800,
      hp: 800,
      maxMana: 450,
      mana: 450,
      manaRegen: 80,
      speed: 1000,
      baseAttackDamage: 85,
      attackRange: 130,
      attackSpeed: 2.1,
    },
    abilities: [
      {
        id: AbilityKey.A,
        name: 'Shadow Dagger',
        description: 'Throws a concealed blade.',
        cooldown: 500,
        currentCooldown: 0,
        manaCost: 10,
        damage: 55,
        type: 'projectile',
        speed: 2500,
        range: 600,
        color: '#7b1fa2',
        icon: '🗡️',
      },
      {
        id: AbilityKey.S,
        name: 'Ghost Walk',
        description: 'Teleports through the void.',
        cooldown: 3500,
        currentCooldown: 0,
        manaCost: 40,
        damage: 0,
        type: 'dash',
        range: 450,
        color: '#9c27b0',
        icon: '👣',
        bypassesWalls: true
      },
      {
        id: AbilityKey.D,
        name: 'Umbral Burst',
        description: 'Slows nearby enemies.',
        cooldown: 4500,
        currentCooldown: 0,
        manaCost: 50,
        damage: 70,
        type: 'aoe',
        radius: 160,
        color: '#4a148c',
        icon: '🌑',
        effect: { type: StatusType.SLOW, timer: 1500, value: 0.7 }
      },
      {
        id: AbilityKey.F,
        name: 'Reaper Strike',
        description: 'Massive damage and stun.',
        cooldown: 12000,
        currentCooldown: 0,
        manaCost: 100,
        damage: 400,
        type: 'aoe',
        radius: 200,
        color: '#000000',
        icon: '💀',
        effect: { type: StatusType.STUN, timer: 1200 }
      }
    ]
  },
  {
    id: 'lyra',
    name: 'Lyra',
    role: 'Crystal Sentinel',
    bio: 'Constructed from rare focusing crystals, Lyra projects defensive barriers and prismatic beams.',
    difficulty: 2,
    color: '#00bcd4',
    accentColor: '#e91e63',
    modelType: 'ranger',
    avatar: 'https://images.unsplash.com/photo-1533134486753-c833f0ed4866?auto=format&fit=crop&q=80&w=400&h=400',
    stats: {
      maxHp: 1100,
      hp: 1100,
      maxMana: 600,
      mana: 600,
      manaRegen: 55,
      speed: 800,
      baseAttackDamage: 55,
      attackRange: 500,
      attackSpeed: 1.4,
    },
    abilities: [
      {
        id: AbilityKey.A,
        name: 'Prism Beam',
        description: 'Fires a refracting laser.',
        cooldown: 350,
        currentCooldown: 0,
        manaCost: 20,
        damage: 50,
        type: 'projectile',
        speed: 2400,
        range: 1100,
        color: '#00e5ff',
        icon: '💎',
      },
      {
        id: AbilityKey.S,
        name: 'Crystal Guard',
        description: 'Generates a light shield.',
        cooldown: 6000,
        currentCooldown: 0,
        manaCost: 50,
        damage: 0,
        type: 'self-buff',
        color: '#ff4081',
        icon: '🛡️',
        effect: { type: StatusType.SHIELD, timer: 4000, value: 450 }
      },
      {
        id: AbilityKey.D,
        name: 'Fracture Field',
        description: 'Creates a slowing crystal zone.',
        cooldown: 5000,
        currentCooldown: 0,
        manaCost: 60,
        damage: 40,
        type: 'target-delayed',
        radius: 180,
        color: '#f50057',
        icon: '❄️',
        effect: { type: StatusType.SLOW, timer: 2000, value: 0.5 }
      },
      {
        id: AbilityKey.F,
        name: 'Solar Flare',
        description: 'Blinds and damages in a huge area.',
        cooldown: 11000,
        currentCooldown: 0,
        manaCost: 90,
        damage: 300,
        type: 'aoe',
        radius: 350,
        color: '#ffffff',
        icon: '✨',
      }
    ]
  },
  {
    id: 'kratos',
    name: 'Kratos',
    role: 'Volt Vanguard',
    bio: 'Harnessing the electrical storms of a gas giant, Kratos moves with thunderous intensity.',
    difficulty: 2,
    color: '#ffd600',
    accentColor: '#2979ff',
    modelType: 'warrior',
    avatar: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=400&h=400',
    stats: {
      maxHp: 1300,
      hp: 1300,
      maxMana: 400,
      mana: 400,
      manaRegen: 65,
      speed: 900,
      baseAttackDamage: 75,
      attackRange: 180,
      attackSpeed: 1.5,
    },
    abilities: [
      {
        id: AbilityKey.A,
        name: 'Static Bolt',
        description: 'Shoots a spark of energy.',
        cooldown: 300,
        currentCooldown: 0,
        manaCost: 15,
        damage: 40,
        type: 'projectile',
        speed: 2600,
        range: 750,
        color: '#ffff00',
        icon: '⚡',
      },
      {
        id: AbilityKey.S,
        name: 'Thunder Dash',
        description: 'Zaps forward at light speed.',
        cooldown: 3000,
        currentCooldown: 0,
        manaCost: 30,
        damage: 30,
        type: 'dash',
        range: 350,
        color: '#00b0ff',
        icon: '☄️',
      },
      {
        id: AbilityKey.D,
        name: 'Overcharge',
        description: 'Increases speed temporarily.',
        cooldown: 6000,
        currentCooldown: 0,
        manaCost: 40,
        damage: 0,
        type: 'self-buff',
        color: '#2979ff',
        icon: '🔋',
        effect: { type: StatusType.SPEED, timer: 3000, value: 400 }
      },
      {
        id: AbilityKey.F,
        name: 'Storm Breach',
        description: 'Summons a lightning strike.',
        cooldown: 9000,
        currentCooldown: 0,
        manaCost: 85,
        damage: 350,
        type: 'target-delayed',
        radius: 160,
        color: '#ffffff',
        icon: '🌩️',
        effect: { type: StatusType.STUN, timer: 800 }
      }
    ]
  }
];
